<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-LSUVMN2" name="Opal1" tests="7" failures="1" timestamp="13 Nov 2019 10:33:49 GMT" time="42.944" errors="0">
  <testcase name="step_0" time="15.591" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_1" time="4.085" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_2" time="3.923" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_3" time="2.135" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_4" time="10.426" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_5" time="3.576" classname="AutomationExModule.AutomationExFeature.AutomationPassScript"/>
  <testcase name="step_6" time="3.173" classname="AutomationExModule.AutomationExFeature.AutomationPassScript">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
null">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
null
	at reuseablePackage.feature.AllActions.AssertAll(AllActions.java:1339)
	at AutomationExModule.AutomationExFeature.AutomationPassScript.step_6(AutomationPassScript.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- step_6 -->
</testsuite> <!-- Opal1 -->
